export const classPeople = {
    'b1a': { rk: 'koll', rk2: 'generalen', fadderk: 'louise', mediak: 'Memory', propp: 'lovisa' },
    'b1b': { rk: 'koll', rk2: 'generalen', fadderk: 'louise', mediak: 'Memory', propp: 'ellen' },
    'b1c': { rk: 'koll', rk2: 'generalen', fadderk: 'louise', mediak: 'Memory', propp: 'rebecca' },
    // B1C -- Propp är placeholder!
    'dv1a': { rk: 'binär', fadderk: 'hampus', mediak: 'Konvex', propp: 'fredrik', },
    'dv1b': { rk: 'binär', fadderk: 'hampus', mediak: 'Konvex', propp: 'klara', },
    'e1a': { rk: 'bläck', fadderk: 'vendela', mediak: 'Konvex', propp: 'oscar', },
    'ei1a': { rk: 'bläck', fadderk: 'vendela', mediak: 'Konvex', propp: 'inna', },
    'es1a': { rk: 'fi', rk2: 'aktören', fadderk: 'erik', mediak: 'Effekten', propp: 'gustav', },
    'es1b': { rk: 'fi', rk2: 'aktören', fadderk: 'erik', mediak: 'Effekten', propp: 'kajsa', },
    'f1a': { rk: 'taesk', rk2: 'kalaspinglan', fadderk: 'simon', mediak: 'Saxen', propp: 'alan', },
    'f1b': { rk: 'taesk', rk2: 'kalaspinglan', fadderk: 'simon', mediak: 'Saxen', propp: 'daniel', },
    'f1c': { rk: 'taesk', rk2: 'kalaspinglan', fadderk: 'simon', mediak: 'Saxen', propp: 'oscar', },
    'f1d': { rk: 'taesk', rk2: 'kalaspinglan', fadderk: 'simon', mediak: 'Saxen', propp: 'anton', },
     // F1D -- Propp är placeholder!
    'i1a': { rk: 'busF', fadderk: 'albin', mediak: 'Producenten', propp: 'victor' },
    'i1b': { rk: 'busF', fadderk: 'albin', mediak: 'Producenten', propp: 'amanda' },
    'it1a': { rk: 'busT', rk2: 'spänn', fadderk: 'maja', mediak: 'Play', propp: 'ulrika' },
    'it1b': { rk: 'busT', rk2: 'spänn', fadderk: 'maja', mediak: 'Play', propp: 'sofia' },
    'it1c': { rk: 'busT', rk2: 'spänn', fadderk: 'maja', mediak: 'Play', propp: 'hanna' },
    'k1a': { rk: 'sting', fadderk: 'elina', mediak: 'Action', propp: 'mattias' },
    'k1b': { rk: 'sting', fadderk: 'elina', mediak: 'Action', propp: 'zackarias' },
    'm1a': { rk: 'sponsT', fadderk: 'aria', mediak: 'Konkav', propp: 'lotta' },
    'm1b': { rk: 'sponsT', fadderk: 'aria', mediak: 'Konkav', propp: 'emma' },
    'mt1a': { rk: 'fix', fadderk: 'sophia', mediak: 'Memory', propp: 'cecilia' },
    'q1a': { rk: 'krims', fadderk: 'alma', mediak: 'Producenten', propp: 'colin' },
    'sts1a': { rk: 'sponsF', rk2: 'köx', fadderk: 'linnea', mediak: 'Effekten', propp: 'johan' },
    'sts1b': { rk: 'sponsF', rk2: 'köx', fadderk: 'linnea', mediak: 'Effekten', propp: 'lovisa' },
    'sts1c': { rk: 'sponsF', rk2: 'köx', fadderk: 'linnea', mediak: 'Effekten', propp: 'siri' },
    'w1a': { rk: 'krams', fadderk: 'daniel', mediak: 'Konkav', propp: 'julia' },
    'w1b': { rk: 'krams', fadderk: 'daniel', mediak: 'Konkav', propp: 'malin' },
    'x1a': { rk: 'markören', rk2: 'skum', fadderk: 'joel', mediak: 'Action', propp: 'karl' },
    'x1b': { rk: 'markören', rk2: 'skum', fadderk: 'joel', mediak: 'Action', propp: 'tyra' },
}
